// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbEjiLdPSKk9qBuRljxukplksve9Q981Q',
    appId: '1:1059217254292:web:ed8f9a4671c6c4e9629181',
    messagingSenderId: '1059217254292',
    projectId: 'iot2024-c31d1',
    authDomain: 'iot2024-c31d1.firebaseapp.com',
    databaseURL: 'https://iot2024-c31d1-default-rtdb.firebaseio.com',
    storageBucket: 'iot2024-c31d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4bWr1rJAmBmUhR66Pbbnj4wocw16T4n8',
    appId: '1:1059217254292:android:9cdaf986aabba639629181',
    messagingSenderId: '1059217254292',
    projectId: 'iot2024-c31d1',
    databaseURL: 'https://iot2024-c31d1-default-rtdb.firebaseio.com',
    storageBucket: 'iot2024-c31d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCPca0cJ0xWrRAHifNg4cFG19gADGUovo',
    appId: '1:1059217254292:ios:e447753adf9df22a629181',
    messagingSenderId: '1059217254292',
    projectId: 'iot2024-c31d1',
    databaseURL: 'https://iot2024-c31d1-default-rtdb.firebaseio.com',
    storageBucket: 'iot2024-c31d1.firebasestorage.app',
    iosBundleId: 'dev.ericamila.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCPca0cJ0xWrRAHifNg4cFG19gADGUovo',
    appId: '1:1059217254292:ios:e447753adf9df22a629181',
    messagingSenderId: '1059217254292',
    projectId: 'iot2024-c31d1',
    databaseURL: 'https://iot2024-c31d1-default-rtdb.firebaseio.com',
    storageBucket: 'iot2024-c31d1.firebasestorage.app',
    iosBundleId: 'dev.ericamila.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbEjiLdPSKk9qBuRljxukplksve9Q981Q',
    appId: '1:1059217254292:web:1b5ed0ef372965dd629181',
    messagingSenderId: '1059217254292',
    projectId: 'iot2024-c31d1',
    authDomain: 'iot2024-c31d1.firebaseapp.com',
    databaseURL: 'https://iot2024-c31d1-default-rtdb.firebaseio.com',
    storageBucket: 'iot2024-c31d1.firebasestorage.app',
  );

}